spring:
  #Mysql DB Connection Settings
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  #JPA Settings
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2
  data:
    web:
      pageable:
        one-indexed-parameters: true
#Embed Tomcat Settings
server:
  port: 8888
